version: "3.9"
services:
  api:
    build: ../api
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  worker:
    build: ../worker
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    working_dir: /app
    command: celery -A app.worker worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: audio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:

