name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: Backend (Python) Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (libsndfile for soundfile)
        run: sudo apt-get update && sudo apt-get install -y libsndfile1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Best-effort install (some tests self-install dependencies)
          pip install -r api/requirements.txt || true
          pip install -r worker/requirements.txt || true

      - name: Compile Python files
        run: python -m compileall -q .

      - name: Run algorithm and storage tests
        env:
          STORAGE_ENDPOINT_URL: http://localhost:9000
          STORAGE_ACCESS_KEY: minioadmin
          STORAGE_SECRET_KEY: minioadmin
          STORAGE_BUCKET_NAME: audio-files
          STORAGE_REGION: us-east-1
          DATABASE_URL: postgresql://user:pass@localhost:5432/audio
          QUEUE_URL: redis://localhost:6379/0
        run: |
          python test_storage_local.py
          python test_audio_processing.py

  frontend:
    name: Frontend (Node) Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: true
          REACT_APP_API_URL: http://localhost:8080
        run: npm run build

